// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Date_Message is the predicate function for date_message builders.
type Date_Message func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
