import type { Metadata } from "next";
import { Providers } from "./components/providers";
import { RootLayoutEntity } from "./components/root-layout-entity";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <RootLayoutEntity>{children}</RootLayoutEntity>
        </Providers>
      </body>
    </html>
  );
}
