package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"

	"github.com/google/uuid"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, userID *uuid.UUID) (uuid.UUID, error) {
	// first login
	if userID == nil {
		u, err := r.client.User.Create().Save(ctx)
		if err != nil {
			return uuid.Nil, err
		}
		return u.ID, nil
	}

	u, err := r.client.User.Get(ctx, *userID)
	if err != nil {
		return uuid.Nil, err
	}
	return u.ID, nil
}
