package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"backend/ent"
	"context"
)

// MessagesByDate is the resolver for the messages_by_date field.
func (r *queryResolver) MessagesByDate(ctx context.Context) ([]*ent.Date_Message, error) {
	return r.client.Date_Message.Query().All(ctx)
}
