package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"

	"github.com/google/uuid"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context) (uuid.UUID, error) {
	u, err := r.client.User.Create().Save(ctx)
	if err != nil {
		return uuid.Nil, err
	}
	return u.ID, err
}
