// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/date_message"
	"backend/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DateMessageDelete is the builder for deleting a Date_Message entity.
type DateMessageDelete struct {
	config
	hooks    []Hook
	mutation *DateMessageMutation
}

// Where appends a list predicates to the DateMessageDelete builder.
func (dmd *DateMessageDelete) Where(ps ...predicate.Date_Message) *DateMessageDelete {
	dmd.mutation.Where(ps...)
	return dmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dmd *DateMessageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dmd.sqlExec, dmd.mutation, dmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dmd *DateMessageDelete) ExecX(ctx context.Context) int {
	n, err := dmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dmd *DateMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(date_message.Table, sqlgraph.NewFieldSpec(date_message.FieldID, field.TypeUUID))
	if ps := dmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dmd.mutation.done = true
	return affected, err
}

// DateMessageDeleteOne is the builder for deleting a single Date_Message entity.
type DateMessageDeleteOne struct {
	dmd *DateMessageDelete
}

// Where appends a list predicates to the DateMessageDelete builder.
func (dmdo *DateMessageDeleteOne) Where(ps ...predicate.Date_Message) *DateMessageDeleteOne {
	dmdo.dmd.mutation.Where(ps...)
	return dmdo
}

// Exec executes the deletion query.
func (dmdo *DateMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := dmdo.dmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{date_message.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dmdo *DateMessageDeleteOne) ExecX(ctx context.Context) {
	if err := dmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
