// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/date_message"
	"backend/ent/message"
	"context"

	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (dm *DateMessageQuery) CollectFields(ctx context.Context, satisfies ...string) (*DateMessageQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return dm, nil
	}
	if err := dm.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return dm, nil
}

func (dm *DateMessageQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(date_message.Columns))
		selectedFields = []string{date_message.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "messages":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&MessageClient{config: dm.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, messageImplementors)...); err != nil {
				return err
			}
			dm.WithNamedMessages(alias, func(wq *MessageQuery) {
				*wq = *query
			})
		case "createdAt":
			if _, ok := fieldSeen[date_message.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, date_message.FieldCreatedAt)
				fieldSeen[date_message.FieldCreatedAt] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		dm.Select(selectedFields...)
	}
	return nil
}

type dateMessagePaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []Date_MessagePaginateOption
}

func newDate_MessagePaginateArgs(rv map[string]any) *dateMessagePaginateArgs {
	args := &dateMessagePaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (m *MessageQuery) CollectFields(ctx context.Context, satisfies ...string) (*MessageQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return m, nil
	}
	if err := m.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return m, nil
}

func (m *MessageQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(message.Columns))
		selectedFields = []string{message.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "user":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: m.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			m.withUser = query
			if _, ok := fieldSeen[message.FieldUserID]; !ok {
				selectedFields = append(selectedFields, message.FieldUserID)
				fieldSeen[message.FieldUserID] = struct{}{}
			}

		case "dateMessage":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&DateMessageClient{config: m.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, date_messageImplementors)...); err != nil {
				return err
			}
			m.withDateMessage = query
			if _, ok := fieldSeen[message.FieldDateID]; !ok {
				selectedFields = append(selectedFields, message.FieldDateID)
				fieldSeen[message.FieldDateID] = struct{}{}
			}
		case "userID":
			if _, ok := fieldSeen[message.FieldUserID]; !ok {
				selectedFields = append(selectedFields, message.FieldUserID)
				fieldSeen[message.FieldUserID] = struct{}{}
			}
		case "content":
			if _, ok := fieldSeen[message.FieldContent]; !ok {
				selectedFields = append(selectedFields, message.FieldContent)
				fieldSeen[message.FieldContent] = struct{}{}
			}
		case "createdAt":
			if _, ok := fieldSeen[message.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, message.FieldCreatedAt)
				fieldSeen[message.FieldCreatedAt] = struct{}{}
			}
		case "dateID":
			if _, ok := fieldSeen[message.FieldDateID]; !ok {
				selectedFields = append(selectedFields, message.FieldDateID)
				fieldSeen[message.FieldDateID] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		m.Select(selectedFields...)
	}
	return nil
}

type messagePaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []MessagePaginateOption
}

func newMessagePaginateArgs(rv map[string]any) *messagePaginateArgs {
	args := &messagePaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (u *UserQuery) CollectFields(ctx context.Context, satisfies ...string) (*UserQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return u, nil
	}
	if err := u.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return u, nil
}

func (u *UserQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "messages":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&MessageClient{config: u.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, messageImplementors)...); err != nil {
				return err
			}
			u.WithNamedMessages(alias, func(wq *MessageQuery) {
				*wq = *query
			})
		}
	}
	return nil
}

type userPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []UserPaginateOption
}

func newUserPaginateArgs(rv map[string]any) *userPaginateArgs {
	args := &userPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	return args
}

const (
	afterField     = "after"
	firstField     = "first"
	beforeField    = "before"
	lastField      = "last"
	orderByField   = "orderBy"
	directionField = "direction"
	fieldField     = "field"
	whereField     = "where"
)

func fieldArgs(ctx context.Context, whereInput any, path ...string) map[string]any {
	field := collectedField(ctx, path...)
	if field == nil || field.Arguments == nil {
		return nil
	}
	oc := graphql.GetOperationContext(ctx)
	args := field.ArgumentMap(oc.Variables)
	return unmarshalArgs(ctx, whereInput, args)
}

// unmarshalArgs allows extracting the field arguments from their raw representation.
func unmarshalArgs(ctx context.Context, whereInput any, args map[string]any) map[string]any {
	for _, k := range []string{firstField, lastField} {
		v, ok := args[k]
		if !ok || v == nil {
			continue
		}
		i, err := graphql.UnmarshalInt(v)
		if err == nil {
			args[k] = &i
		}
	}
	for _, k := range []string{beforeField, afterField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		c := &Cursor{}
		if c.UnmarshalGQL(v) == nil {
			args[k] = c
		}
	}
	if v, ok := args[whereField]; ok && whereInput != nil {
		if err := graphql.UnmarshalInputFromContext(ctx, v, whereInput); err == nil {
			args[whereField] = whereInput
		}
	}

	return args
}

// mayAddCondition appends another type condition to the satisfies list
// if it does not exist in the list.
func mayAddCondition(satisfies []string, typeCond []string) []string {
Cond:
	for _, c := range typeCond {
		for _, s := range satisfies {
			if c == s {
				continue Cond
			}
		}
		satisfies = append(satisfies, c)
	}
	return satisfies
}
